# Generated by Django 3.0.3 on 2020-02-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sctfuser',
            options={'permissions': [('view_all_users', 'Can view all users in database'), ('edit_all_users', 'Can edit all the users'), ('delete_all_users', 'Can delete any and all users'), ('view_own_user', 'Can view own user information'), ('edit_own_user', 'Can edit own user information'), ('delete_own_user', 'Can delete own user information')]},
        ),
    ]
