# Generated by Django 3.0.3 on 2020-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200331_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sctfuser',
            name='new_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sctfuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
