# Generated by Django 3.0.3 on 2020-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200223_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='expiry_data',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='id',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='key',
            field=models.CharField(default=0, max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
