# Generated by Django 3.0.3 on 2020-02-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20200224_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
