# Generated by Django 3.0.3 on 2020-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_delete_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='enc_username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeviceVerification',
        ),
    ]
